{"icons":[
{"cat":"none", "text":"none", "url":"mapicons/direction_downleft.png"}
,{"cat":"none", "text":"none","url":"mapicons/direction_down.png"}
,{"cat":"none", "text":"none","url":"mapicons/direction_downright.png"}
,{"cat":"none", "text":"none","url":"mapicons/direction_left.png"}
,{"cat":"none", "text":"none","url":"mapicons/direction_right.png"}
,{"cat":"none", "text":"none","url":"mapicons/direction_upleft.png"}
,{"cat":"none", "text":"none","url":"mapicons/direction_up.png"}
,{"cat":"none", "text":"none","url":"mapicons/direction_upright.png"}
,{"cat":"none", "text":"none","url":"mapicons/accesdenied.png"}
,{"cat":"none", "text":"none","url":"mapicons/caution.png"}
,{"cat":"none", "text":"none","url":"mapicons/bus.png"}
,{"cat":"none", "text":"none","url":"mapicons/parkinggarage.png"}
,{"cat":"none", "text":"none","url":"mapicons/firstaid.png"}
,{"cat":"none", "text":"none","url":"mapicons/emergencyphone.png"}
,{"cat":"none", "text":"none","url":"mapicons/ambulance.png"}
,{"cat":"none", "text":"none","url":"mapicons/hospital-building.png"}
,{"cat":"none", "text":"none","url":"mapicons/medicine.png"}
,{"cat":"none", "text":"none","url":"mapicons/school.png"}
,{"cat":"none", "text":"none","url":"mapicons/communitycentre.png"}
,{"cat":"none", "text":"none","url":"mapicons/seniorsite.png"}
,{"cat":"none", "text":"none","url":"mapicons/family.png"}
,{"cat":"none", "text":"none","url":"mapicons/daycare.png"}
,{"cat":"none", "text":"none","url":"mapicons/blast.png"}
,{"cat":"none", "text":"none","url":"mapicons/skull.png"}
,{"cat":"none", "text":"none","url":"mapicons/earthquake-3.png"}
,{"cat":"none", "text":"none","url":"mapicons/poweroutage.png"}
,{"cat":"none", "text":"none","url":"mapicons/fire.png"}
,{"cat":"none", "text":"none","url":"mapicons/flood.png"}
,{"cat":"none", "text":"none","url":"mapicons/radio-station-2.png"}
,{"cat":"none", "text":"none","url":"mapicons/regroup.png"}
,{"cat":"none", "text":"none","url":"mapicons/wifi.png"}
,{"cat":"none", "text":"none","url":"mapicons/group-2.png"}
,{"cat":"none", "text":"none","url":"mapicons/firemen.png"}
,{"cat":"none", "text":"none","url":"mapicons/police.png"}
,{"cat":"none", "text":"none","url":"mapicons/cctv.png"}
,{"cat":"none", "text":"none","url":"mapicons/moderntower.png"}
,{"cat":"none", "text":"none","url":"mapicons/comment-map-icon.png"}
,{"cat":"none", "text":"none","url":"mapicons/smiley_happy.png"}
]}      
